target 'ChatKit-OC' do
  platform :ios , '8.0'
  inhibit_all_warnings!

  #=========================================================
  #======================== Lib Dependency =================
  #=========================================================
  pod 'CYLChatKit', :path => '../'
#  pod 'AVOSCloud', :path => '../../objc-sdk'
#  pod 'AVOSCloudIM', :path => '../../objc-sdk'

  #=========================================================
  #======================== Demo Dependency ================
  #=========================================================

  pod 'CYLTabBarController', '1.17.11'
  pod 'TWMessageBarManager', '1.8.1'
  pod 'MLPAutoCompleteTextField', '1.5'
  pod 'FTPopOverMenu', '1.3.2'
  pod 'RedpacketLib' ,'3.4.1'
  pod 'FXForms', '1.2.14'
  #pod "CYLMWPhotoBrowser", "~> 2.1.2-0.0.5" 
end
